### ISSUE TITLE
Select Mono_date not work

### ISSUE THREAD

**Issue by ron8520** [VSainteuf/pastis-benchmark#14] opened 2022-08-13 15:52 UTC
Hi, I want only to select the particular date of images rather than a series. By setting attribute mono_date = "2018-09-02" on PASTIS_Dataset(). It raises 

`Unsupported operand types(s) for -: 'dict' and 'int'` error

**Comment by VSainteuf** [comment] 2022-08-31 09:33
Hi @ron8520 ,
Thanks for pointing this out, I think I know what the problem is, let me get back to you shortly.

**Comment by VSainteuf** [comment] 2022-08-31 11:54
Hey, I fixed the problem and also pushed the fix to the utae-paps repository. 
Can you confirm it works for you too now ?

**Closed** 2022-09-08 15:24 UTC
